export const ROUTES = {
  dashboard:    '/',
  upload:       '/upload',
  project:      '/project',
  history:      '/history',
  comparison:   '/comparison',
  impact:       '/impact',
  architecture: '/architecture',
  frontend:     '/frontend',
  backend:      '/backend',
  database:     '/database',
  components:   '/components',
  hooks:        '/hooks',
  apis:         '/apis',
  dependencies: '/dependencies',
  modules:      '/modules',
  prompts:      '/prompts',
  settings:     '/settings',
};
